-- 初始数据导入

-- 装备库
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('longsword', '长剑', '武器', '{"id":"longsword","name":"长剑","category":"武器","subtype":"军用武器","weight":3,"price":{"amount":15,"unit":"gp"},"description":"这是一种直刃剑，比短剑更长。单手持握或与盾牌、另一把剑配合使用。你用该武器进行的攻击命中时，造成 1d8 点挥砍伤害。","properties":["多功能","单手/双手"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('shortsword', '短剑', '武器', '{"id":"shortsword","name":"短剑","category":"武器","subtype":"简易武器","weight":2,"price":{"amount":10,"unit":"gp"},"description":"短剑是一种小型直刃剑。单手持握时视为一把简易近战武器。","properties":["灵巧","轻型"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('bow', '长弓', '武器', '{"id":"bow","name":"长弓","category":"武器","subtype":"远程武器","weight":2,"price":{"amount":50,"unit":"gp"},"description":"这是一种大型木质弓。持弓者若想用该武器拉弓，必须用空出一只手来拉弦。此伤害适用于普通射程 150 尺，Long 射程 600 尺。","properties":["弹药","150/600尺"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('leather-armor', '皮甲', '护甲', '{"id":"leather-armor","name":"皮甲","category":"护甲","subtype":"轻甲","weight":10,"price":{"amount":45,"unit":"gp"},"description":"护甲由涂蜡的皮革制成，胸甲和肩甲处通常饰有铆钉。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('chain-mail', '链甲衫', '护甲', '{"id":"chain-mail","name":"链甲衫","category":"护甲","subtype":"中甲","weight":55,"price":{"amount":75,"unit":"gp"},"description":"此类护甲由互相连锁的金属环组成，穿在衬衣外以防止刀剑砍伤和大多数钝击伤害。穿着时若生命值降至 0 ，或受到一次重击伤害，你可以进行一次体质豁免（DC = 8 + 受到的伤害值），豁免成功则护甲只受耐久度损耗而不降低生命值。","properties":["中甲"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('plate-armor', '板甲', '护甲', '{"id":"plate-armor","name":"板甲","category":"护甲","subtype":"重甲","weight":65,"price":{"amount":1500,"unit":"gp"},"description":"此护甲由相互连锁的金属板组成，覆盖全身。穿戴板甲需要大量的训练，不过穿着者可以从中获得完善的保护。","properties":["重甲"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('shield', '盾牌', '护甲', '{"id":"shield","name":"盾牌","category":"护甲","subtype":"盾牌","weight":6,"price":{"amount":10,"unit":"gp"},"description":"持握盾牌时，你的 AC 获得 +2 加值。你一次只能使用一件属于持用类型的物品。","properties":["+2 AC"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('healing-potion', '治疗药水', '药水', '{"id":"healing-potion","name":"治疗药水","category":"药水","subtype":"治疗药水","weight":0.5,"price":{"amount":50,"unit":"gp"},"description":"使你恢复 2d4+2 点生命值。","properties":["治疗","2d4+2 HP"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('thieves-tools', '盗贼工具', '工具', '{"id":"thieves-tools","name":"盗贼工具","category":"工具","subtype":"盗贼工具","weight":1,"price":{"amount":25,"unit":"gp"},"description":"该工具集包括一把小锉刀、一把撬锁工具、一面小镜子、一把尖锐镐子以及一卷内藏拔丝的纱线。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('spellbook', '法术书', '法器', '{"id":"spellbook","name":"法术书","category":"法器","subtype":"奥术法器","weight":3,"price":{"amount":50,"unit":"gp"},"description":"法师的法术书是带有羊皮纸书页的精装本。法术书首页饰有墨迹优雅的奇异符文。法术书包含至少100页。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('component-pouch', '材料袋', '法器', '{"id":"component-pouch","name":"材料袋","category":"法器","subtype":"材料袋","weight":2,"price":{"amount":25,"unit":"gp"},"description":"这是一种小型防水腰袋，内衬毛皮，用于盛放各类法术材料组分。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('holy-symbol', '圣徽', '法器', '{"id":"holy-symbol","name":"圣徽","category":"法器","subtype":"圣徽","weight":1,"price":{"amount":5,"unit":"gp"},"description":"圣徽可以是圣者雕像般的垂饰，也可以是信徒展示于脖间或手持的象征图形。当持握该物件时，你的牧师或圣武士法术在施法时不需要使用该法术对应的材料构材。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('rope', '绳索', '杂物', '{"id":"rope","name":"绳索","category":"杂物","subtype":"绳索","weight":10,"price":{"amount":1,"unit":"gp"},"description":"绳索由黄麻纤维拧制而成，最多可承受2000磅重量。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('torch', '火把', '杂物', '{"id":"torch","name":"火把","category":"杂物","subtype":"照明","weight":1,"price":{"amount":1,"unit":"cp"},"description":"一根木头或布浸透了易燃液体。一根火把可持续燃烧1小时，提供正常光照20尺范围和昏暗光照20尺范围的亮度。","properties":["照明","1小时"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('backpack', '背包', '杂物', '{"id":"backpack","name":"背包","category":"杂物","subtype":"容器","weight":5,"price":{"amount":2,"unit":"gp"},"description":"这是一种皮制或布制背包，可以绑在身上以方便携带物品。背包可以容纳约1立方英尺的物体或30磅重量。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('crowbar', '撬棍', '杂物', '{"id":"crowbar","name":"撬棍","category":"杂物","subtype":"工具","weight":5,"price":{"amount":2,"unit":"gp"},"description":"使用撬棍在窄缝处施力可以提供2d6点力量伤害。撬棍还能让你在对抗以DC 10敏捷豁免的陷阱上占有优势。","properties":["优势(撬锁)"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('mage-staff', '法杖', '法器', '{"id":"mage-staff","name":"法杖","category":"法器","subtype":"法杖","weight":4,"price":{"amount":50,"unit":"gp"},"description":"法杖可由特定职业施法者用来当作施法法器。不同的法杖拥有不同的属性和增益效果。","properties":[],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO equipments (id, name, category, data, created_at, updated_at) VALUES ('greataxe', '巨斧', '武器', '{"id":"greataxe","name":"巨斧","category":"武器","subtype":"军用武器","weight":7,"price":{"amount":30,"unit":"gp"},"description":"双手挥动的大型战斧，威力巨大。你用该武器进行的攻击命中时，造成 1d12 点挥砍伤害。","properties":["重型","双手"],"isCustom":false,"tags":[],"source":"玩家手册"}', 1782998417144, 1782998417144);

-- 法术库
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('dancing-lights', '舞光术', 0, '塑能系', '{"id":"dancing-lights","name":"舞光术","level":0,"school":"塑能系","castingTime":"1个动作","range":"120尺","components":{"verbal":true,"somatic":true,"material":false},"duration":"1分钟","description":"你造出最多四个像火把大小的光点，让它们悬浮在射程内的空中。你也可以把两个光点组合成一个类人生物的发光外形，大概和矮人一样大。不管哪种形式，这些光源都存在到法术终止为止。\n\n每个火把大小的光源会在10尺半径内散出亮光照度，另10尺半径内散出微光照度。你可以用一个附赠动作将光源移动至射程内任意位置。当光源超出射程时，它会直接消失。","classes":["吟游诗人","术士","法师","术士"],"notes":"戏法，升环无额外效果"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('sacred-flame', '神圣光辉', 0, '塑能系', '{"id":"sacred-flame","name":"神圣光辉","level":0,"school":"塑能系","castingTime":"1个动作","range":"60尺","components":{"verbal":true,"somatic":true,"material":false},"duration":"立即","description":"射程内的一个生物必须进行一次敏捷豁免。若失败，则目标受到1d8点光耀伤害。目标不能从半掩蔽和四分之三掩蔽获得该豁免的优势。\n\n当你到达5级（2d8）、11级（3d8）和17级（4d8）时，此法术的伤害会提升。","classes":["牧师"],"notes":"戏法"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('produce-flame', '燃火术', 0, '塑能系', '{"id":"produce-flame","name":"燃火术","level":0,"school":"塑能系","castingTime":"1个动作","range":"自身","components":{"verbal":false,"somatic":true,"material":false},"duration":"10分钟","description":"你手中摇曳生出一小簇无害的火焰。火焰在法术持续时间内一直存在，不会伤害你或你的装备。\n\n你可以用一个动作将火焰投向射程30尺内的一个生物或物件，然后法术终止。进行一次远程法术攻击。若命中，目标受到1d8点火焰伤害。\n\n当你到达5级（2d8）、11级（3d8）和17级（4d8）时，此法术的伤害会提升。","classes":["德鲁伊"],"notes":"戏法"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('vicious-mockery', '恶语相加', 0, '附魔系', '{"id":"vicious-mockery","name":"恶语相加","level":0,"school":"附魔系","castingTime":"1个动作","range":"60尺","components":{"verbal":true,"somatic":false,"material":false},"duration":"立即","description":"你用言语嘲弄射程内的一个生物，你的话语中夹杂着微妙的魔法诅咒。目标必须进行一次感知豁免。若失败，则直到其下一回合结束前，它下一次攻击检定具有劣势，并且受到 1d4 点心灵伤害。\n\n当你到达5级（2d4）、11级（3d4）和17级（4d4）时，此法术的伤害会提升。","classes":["吟游诗人"],"notes":"戏法，吟游诗人标志性法术"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('sleep', '睡眠术', 1, '附魔系', '{"id":"sleep","name":"睡眠术","level":1,"school":"附魔系","castingTime":"1个动作","range":"90 尺","components":{"verbal":true,"somatic":true,"material":true},"duration":"1分钟","description":"此法术让范围内的生物陷入魔法沉眠。掷5d8；由此得出你能影响的生物总生命值。从当前生命值最低的生物开始，法术按生命值由低到高的顺序影响射程内处于你所选点20尺半径球状范围内的每个生物。\n\n对每个受影响的生物，从其总生命值中减去其当前生命值。在总值耗尽前，生物一直处于魔法睡眠状态。只有当前生命值为0或已经陷入睡眠的生物会被此法术影响。\n","classes":["吟游诗人","术士","法师","术士"],"notes":"","hasHeightened":true,"materialInfo":"一把细沙、玫瑰花瓣或一只蟋蟀","heightenedEffect":"2 环或更高环位施展此法术时，每高 1 环多掷 2d8。"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('charm-person', '魅惑人类', 1, '附魔系', '{"id":"charm-person","name":"魅惑人类","level":1,"school":"附魔系","castingTime":"1 动作","range":"30 尺","components":{"verbal":true,"somatic":true,"material":false},"duration":"1 小时","description":"你尝试魅惑施法距离内的某个你能看见的类人生物。该生物必须进行一次感知豁免。如果你或你的同伴正在和该生物战斗，则该生物进行该豁免时具有优势。如果豁免失败，则该生物被你魅惑至法术终止，或者直到你或你的同伴对他做出伤害行为为止。此间，被魅惑的生物将视你为友方且熟悉的人。法术终止后，该生物将会发觉曾被你魅惑过。","classes":["吟游诗人","德鲁伊","术士","法师"],"notes":"","hasHeightened":true,"heightenedEffect":"2 环或更高法术位施展该法术时，你使用的法术位每比一环高一环，法术就能多影响一个目标。而各目标之间距离不能超过 30 尺。"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('invisibility', '隐形术', 2, '幻术系', '{"id":"invisibility","name":"隐形术","level":2,"school":"幻术系","castingTime":"1个动作","range":"接触","components":{"verbal":true,"somatic":true,"material":true},"duration":"1小时","description":"你接触的一个生物在法术持续时间内变得隐形。目标身上穿戴或携带的任何物品，只要在其身上，也同样隐形。\n\n如果目标攻击或施放法术，此法术终止。\n\n升环效应：当你使用3环或更高环位施展此法术时，每高1环可以多指定一个生物。","classes":["吟游诗人","术士","法师","术士"],"notes":"材料成分：一个眼罩，由一小片薄纱制成"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('knock', '敲击术', 2, '变化系', '{"id":"knock","name":"敲击术","level":2,"school":"变化系","castingTime":"1个动作","range":"60尺","components":{"verbal":false,"somatic":false,"material":true},"duration":"立即","description":"选择射程内的一扇门、箱子、柜子或其他由锁或枷锁封闭的物体。目标上最多两个锁被解锁。如果目标只有一个锁，你还可以用它来解锁被奥术锁（arcane lock）魔法封印的目标——但有一次检定机会（你的施法关键属性调整值 + 你的熟练加值）。DC等于施放奥术锁的施法者的豁免DC。如果你在该检定中成功，则奥术锁失效10分钟。\n\n当你施展此法术时，60尺内都能听到响亮的敲击声。","classes":["吟游诗人","术士","法师","术士"],"notes":"材料成分：一块小而碎的骨头"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('misty-step', '迷踪步', 2, '咒法系', '{"id":"misty-step","name":"迷踪步","level":2,"school":"咒法系","castingTime":"1个附赠动作","range":"自身","components":{"verbal":true,"somatic":false,"material":false},"duration":"立即","description":"简短地吟诵咒语，你就能传送到射程内的一处未被占据的空间，该空间必须是你能看到的地方。你可以携带装备，但不能超过你的承载量。你也可以携带一个体型为小或更小的自愿生物，该生物必须在你的10尺范围内，并且装备不得超过其承载量。","classes":["吟游诗人","术士","法师","术士","圣武士","游侠"],"notes":"附赠动作施法，非常实用"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('fireball', '火球术', 3, '塑能系', '{"id":"fireball","name":"火球术","level":3,"school":"塑能系","castingTime":"1个动作","range":"150尺","components":{"verbal":true,"somatic":true,"material":true},"duration":"立即","description":"一道明亮的火焰从你指向的一点爆发，在该点形成一个半径20尺的火球。该区域内的每个生物必须进行一次敏捷豁免。豁免失败的生物受到8d6点火焰伤害，豁免成功则伤害减半。\n\n火球会扩散到角落周围。它会点燃区域内未被穿戴或携带的易燃物。\n\n升环效应：当你使用4环或更高环位施展此法术时，每高1环伤害增加1d6。","classes":["术士","法师","术士"],"notes":"材料成分：一颗硫黄球和一团蝙蝠粪"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('haste', '加速术', 3, '变化系', '{"id":"haste","name":"加速术","level":3,"school":"变化系","castingTime":"1个动作","range":"接触","components":{"verbal":true,"somatic":true,"material":true},"duration":"1分钟","description":"选择一个自愿的生物，在法术持续时间内，其速度翻倍，它的AC获得+2加值，它在敏捷豁免中具有优势，并且它每回合可以额外进行一个动作。该动作只能用于以下选项之一：进行一次武器攻击、冲刺、脱离、躲藏或使用一个物件。\n\n当法术终止时，目标在该回合内不能移动，直到下一个回合为止，它不能进行任何动作。","classes":["吟游诗人","术士","法师","术士"],"notes":"材料成分：一根甘草根"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('counterspell', '反制法术', 3, '塑能系', '{"id":"counterspell","name":"反制法术","level":3,"school":"塑能系","castingTime":"1个反应","range":"60尺","components":{"verbal":true,"somatic":false,"material":false},"duration":"立即","description":"你尝试打断一个正在被施放的法术。如果该法术是3环或更低等级的，则其效果自动失败，没有任何作用。如果它是4环或更高等级，则你必须进行一次施法关键属性检定（DC=10 + 该法术的环阶）。若成功，则该法术失败，没有任何作用。\n\n升环效应：当你使用4环或更高环位施展此法术时，若目标法术的环阶不高于你使用的环位，则该法术自动失败。","classes":["术士","法师","术士","圣武士","游侠"],"notes":"反应动作施放"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('greater-invisibility', '高等隐形术', 4, '幻术系', '{"id":"greater-invisibility","name":"高等隐形术","level":4,"school":"幻术系","castingTime":"1个动作","range":"接触","components":{"verbal":true,"somatic":true,"material":false},"duration":"1分钟","description":"你接触的一个生物在法术持续时间内变得隐形。目标身上穿戴或携带的任何物品，只要在其身上，也同样隐形。与普通隐形术不同，攻击或施法不会终止此法术。","classes":["吟游诗人","术士","法师","术士"],"notes":"攻击和施法不会解除隐形"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('healing-word', '治愈真言', 1, '塑能系', '{"id":"healing-word","name":"治愈真言","level":1,"school":"塑能系","castingTime":"附赠动作","range":"60 尺","components":{"verbal":true,"somatic":false,"material":false},"duration":"立即","description":"你指定施法距离内一个你能看见的生物并恢复其生命值，恢复量等于 1d4+ 你的施法属性调整值。该法术对构装体和不死生物无效。","classes":["牧师","德鲁伊","吟游诗人"],"notes":"","hasHeightened":true,"heightenedEffect":"2 环或更高法术位施展该法术时，你使用的法术位每比一环高一环，治疗量就增加 1d4 点。"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('dissonant-whispers', '不谐低语', 1, '附魔系', '{"id":"dissonant-whispers","name":"不谐低语","level":1,"school":"附魔系","castingTime":"1 个动作","range":"60 尺","components":{"verbal":true,"somatic":false,"material":false},"duration":"立即","description":"你指定一个施法距离内能够听到你声音的生物，并对其说出只有他能听到的不谐低语，使其受强烈的痛苦折磨。目标必须进行一次感知豁免。豁免失败则受到 3d6 点心灵伤害，并立即执行反应往远离你的方向移动其速度所允许的距离。该生物不会进入明显危险的地域，如火堆或陷坑。豁免成功则伤害减半，且不会执行远离的反应。陷入耳聋状态的目标，进行该豁免时直接判定为成功。","classes":["吟游诗人"],"notes":"","hasHeightened":true,"heightenedEffect":"2 环或更高法术位施展该法术时，你使用的法术位每比一环高一环，法术的伤害就增加 1d6。"}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('mage-hand', '法师之手', 0, '咒法系', '{"id":"mage-hand","name":"法师之手","level":0,"school":"咒法系","castingTime":"1 动作","range":"30 尺","components":{"verbal":true,"somatic":true,"material":false},"duration":"1 分钟","description":"一只漂浮的幽灵手出现在施法距离内你指定的一点。幽灵手持续存在至法术终止，或直至你以一个动作解散该法术。如果幽灵手距你的距离超过 30 尺，或者当你再次施展了该法术时，则现存的幽灵手消失不见。\n\n你可以用动作控制幽灵手，并通过幽灵手实现一个行为：你可以操控一个物件，或者打开一扇未上锁的门或容器，或者将一件物品放入容器或从容器中取出，或者将小瓶中的内容物倾倒出来。你每次你使用幽灵手时可以令其移动至多 30 尺。\n\n该幽灵手不能攻击，也不能激活魔法物品或承载超过 10 磅重的物质。","classes":["吟游诗人","术士","法师"],"notes":""}', 1782998417144, 1782998417144);
INSERT OR IGNORE INTO spells (id, name, level, school, data, created_at, updated_at) VALUES ('tashas-hideous-laughter', '塔莎狂笑术', 1, '附魔系', '{"id":"tashas-hideous-laughter","name":"塔莎狂笑术","level":1,"school":"附魔系","castingTime":"1 动作","range":"30 尺","components":{"verbal":true,"somatic":true,"material":true},"duration":"1 分钟","description":"指定施法距离内一个你能看见的生物，如果该生物可受法术影响，则一切事物在该生物眼中都变得滑稽可笑，使它开始狂笑起来。目标必须进行一次感知豁免，豁免失败则俯身倒地，并在法术持续时间内陷入失能状态且无法起立。该效应对智力为 4 或更低的生物无效。\n\n目标在其每回合结束或受到伤害时，可以再进行一次感知豁免。豁免成功则法术终止。再进行豁免时，如果是因受到伤害所致则该次豁免具有优势。","classes":["吟游诗人","法师"],"notes":"","hasHeightened":false,"heightenedEffect":"","materialInfo":"一些小甜饼以及一片空中飘荡的羽毛"}', 1782998417144, 1782998417144);
